version: "3.2"
services:
    app:
        container_name: shoppingcart-api
        build: .
        ports:
          - "5008:8086"
        depends_on: 
          - mysqldb
    mysqldb:
        container_name: shoppingcart-db
        build: mssql/.
        ports:
          - "1433:1433"
        environment:    
          MSSQL_PID: "Developer"
          MSSQL_USER: "sa"
          MSSQL_SA_PASSWORD: "Passw0rd"
          ACCEPT_EULA: "Y"           